// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "GunTour/features/ranger/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: data, dataUser
func (_m *Repository) Add(data domain.Core, dataUser domain.User) (domain.Core, error) {
	ret := _m.Called(data, dataUser)

	var r0 domain.Core
	if rf, ok := ret.Get(0).(func(domain.Core, domain.User) domain.Core); ok {
		r0 = rf(data, dataUser)
	} else {
		r0 = ret.Get(0).(domain.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Core, domain.User) error); ok {
		r1 = rf(data, dataUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: start, end
func (_m *Repository) GetAll(start time.Time, end time.Time) ([]domain.Core, error) {
	ret := _m.Called(start, end)

	var r0 []domain.Core
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []domain.Core); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
