// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "GunTour/features/ranger/domain"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	time "time"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Apply provides a mock function with given fields: data, dataUser, file, fileheader
func (_m *Service) Apply(data domain.Core, dataUser domain.User, file multipart.File, fileheader *multipart.FileHeader) (domain.Core, error) {
	ret := _m.Called(data, dataUser, file, fileheader)

	var r0 domain.Core
	if rf, ok := ret.Get(0).(func(domain.Core, domain.User, multipart.File, *multipart.FileHeader) domain.Core); ok {
		r0 = rf(data, dataUser, file, fileheader)
	} else {
		r0 = ret.Get(0).(domain.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Core, domain.User, multipart.File, *multipart.FileHeader) error); ok {
		r1 = rf(data, dataUser, file, fileheader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShowAll provides a mock function with given fields: start, end
func (_m *Service) ShowAll(start time.Time, end time.Time) ([]domain.Core, error) {
	ret := _m.Called(start, end)

	var r0 []domain.Core
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []domain.Core); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
